<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('pendaftars', function (Blueprint $table) {
            $table->id();

            $table->string('ps_walisantri_id')->nullable();
            $table->string('ps_qism', 2)->nullable();
            $table->string('ps_qism_view', 20)->nullable();
            $table->string('ps_kelas', 2)->nullable();
            $table->string('ps_tahap', 30)->nullable();
            $table->string('ps_desc_tahap', 255)->nullable();
            $table->string('ps_nism', 10)->unique()->nullable();
            $table->boolean('ps_belum_nism')->nullable();
            $table->string('ps_nama_lengkap', 50)->nullable();
            $table->string('ps_nama_panggilan', 50)->nullable();
            $table->string('ps_nisn', 10)->nullable();
            $table->boolean('ps_belum_nisn')->nullable();
            $table->string('ps_kewarganegaraan', 10)->nullable();
            $table->string('ps_asal_negara', 20)->nullable();
            $table->string('ps_kitas', 20)->nullable();
            $table->string('ps_kartu_keluarga', 16)->unique()->nullable();
            $table->string('ps_nik', 16)->unique()->nullable();
            $table->boolean('ps_belum_punya_nik')->nullable();
            $table->string('ps_jeniskelamin', 15)->nullable();
            $table->string('ps_tempat_lahir', 20)->nullable();
            $table->string('ps_tanggal_lahir', 10)->nullable();
            $table->string('ps_umur', 3)->nullable();
            $table->string('ps_agama', 10)->nullable();
            $table->string('ps_cita_cita', 30)->nullable();
            $table->string('ps_cita_cita_lainnya', 30)->nullable();
            $table->string('ps_anak_ke', 2)->nullable();
            $table->string('ps_jumlah_saudara', 2)->nullable();
            $table->boolean('ps_tdk_hp')->nullable();
            $table->string('ps_nomor_handphone', 20)->nullable();
            $table->string('ps_email', 50)->nullable();
            $table->string('ps_akun_medsos', 40)->nullable();
            $table->string('ps_akun_medsos_aktif', 40)->nullable();
            $table->string('ps_hobi', 40)->nullable();
            $table->string('ps_hobi_lainnya', 40)->nullable();
            $table->string('ps_aktivitaspend', 30)->nullable();
            $table->string('ps_peng_pend_agama', 30)->nullable();
            $table->string('ps_peng_pend_formal', 40)->nullable();
            $table->string('ps_bya_sklh', 50)->nullable();
            $table->string('ps_status_mampu', 20)->nullable();
            $table->string('ps_rincian_status_mampu', 255)->nullable();
            $table->string('ps_mendaftar_keinginan', 20)->nullable();
            $table->string('ps_mendaftar_keinginan_lainnya', 20)->nullable();
            $table->string('ps_keb_khus', 50)->nullable();
            $table->text('ps_keb_khus_lainnya')->nullable();
            $table->string('ps_keb_dis', 50)->nullable();
            $table->text('ps_keb_dis_lainnya')->nullable();
            $table->text('ps_peny_fisik')->nullable();
            $table->text('ps_peny_non_fisik')->nullable();
            $table->string('ps_nomor_kip', 20)->nullable();
            $table->string('ps_nama_kpl_kel', 50)->nullable();
            $table->string('ps_file_kip', 20)->nullable();
            $table->string('ps_al_s_status_mukim', 20)->nullable();
            $table->string('ps_al_s_stts_tptgl', 20)->nullable();
            $table->string('ps_provinsi_id', 10)->nullable();
            $table->string('ps_kabupaten_id', 10)->nullable();
            $table->string('ps_kecamatan_id', 10)->nullable();
            $table->string('ps_kelurahan_id', 10)->nullable();
            $table->string('ps_al_s_rt', 10)->nullable();
            $table->string('ps_al_s_rw', 10)->nullable();
            $table->text('ps_al_s_alamat')->nullable();
            $table->string('ps_kodepos', 10)->nullable();
            $table->string('ps_al_s_jarak', 10)->nullable();
            $table->string('ps_al_s_transportasi', 10)->nullable();
            $table->string('ps_al_s_waktu_tempuh', 10)->nullable();
            $table->text('ps_al_s_koordinat')->nullable();
            $table->string('ps_hafalan', 2)->nullable();
            $table->string('ps_kkh_keberadaan', 50)->nullable();
            $table->text('ps_kkh_keberadaan_nama_mhd')->nullable();
            $table->text('ps_kkh_keberadaan_lokasi_mhd')->nullable();
            $table->text('ps_kkh_keberadaan_rumah_keg')->nullable();
            $table->boolean('ps_kkh_fasilitas_gawai')->nullable();
            $table->text('ps_kkh_fasilitas_gawai_medsos')->nullable();
            $table->text('ps_kkh_fasilitas_gawai_medsos_daftar')->nullable();
            $table->text('ps_kkh_fasilitas_gawai_medsos_aktif')->nullable();
            $table->string('ps_kkh_fasilitas_gawai_medsos_menutup', 20)->nullable();
            $table->string('ps_kkh_medsos_sering', 20)->nullable();
            $table->text('ps_kkh_medsos_sering_lainnya')->nullable();
            $table->boolean('ps_kkh_medsos_group')->nullable();
            $table->text('ps_kkh_medsos_group_nama')->nullable();
            $table->text('ps_kkh_medsos_group_bidang_keg')->nullable();
            $table->text('ps_kkh_bacaan')->nullable();
            $table->text('ps_kkh_bacaan_cara_dapat')->nullable();
            $table->boolean('ps_kkes_sakit_serius')->nullable();
            $table->text('ps_kkes_sakit_serius_kapan')->nullable();
            $table->text('ps_kkes_sakit_serius_nama_penyakit')->nullable();
            $table->boolean('ps_kkes_terapi')->nullable();
            $table->text('ps_kkes_terapi_kapan')->nullable();
            $table->text('ps_kkes_terapi_nama_terapi')->nullable();
            $table->boolean('ps_kkes_kambuh')->nullable();
            $table->text('ps_kkes_kambuh_nama_penyakit')->nullable();
            $table->boolean('ps_kkes_alergi')->nullable();
            $table->text('ps_kkes_alergi_nama_alergi')->nullable();
            $table->boolean('ps_kkes_pantangan')->nullable();
            $table->text('ps_kkes_pantangan_nama')->nullable();
            $table->text('ps_kkes_pantangan_alasan')->nullable();
            $table->boolean('ps_kkes_psikologis')->nullable();
            $table->text('ps_kkes_psikologis_kapan')->nullable();
            $table->boolean('ps_kkes_gangguan')->nullable();
            $table->text('ps_kkes_gangguan_kapan')->nullable();
            $table->string('ps_kadm_status', 20)->nullable();
            $table->string('ps_kadm_surat_subsidi', 20)->nullable();
            $table->string('ps_kadm_surat_kurang_mampu', 20)->nullable();
            $table->string('ps_kadm_atur_keuangan', 20)->nullable();
            $table->string('ps_kadm_penentuan_subsidi', 20)->nullable();
            $table->string('ps_kadm_hidup_sederhana', 20)->nullable();
            $table->string('ps_kadm_kebijakan_subsidi', 20)->nullable();
            $table->string('user_id', 20)->nullable();
            $table->string('pw_kartu_keluarga_santri', 16)->nullable();
            $table->string('pw_ak_nama_lengkap', 70)->nullable();
            $table->string('pw_ak_nama_kunyah', 70)->nullable();
            $table->string('pw_ak_status', 50)->nullable();
            $table->string('pw_ak_kewarganegaraan', 10)->nullable();
            $table->string('pw_ak_asal_negara', 50)->nullable();
            $table->string('pw_ak_kitas', 20)->nullable();
            $table->string('pw_ak_nik', 16)->unique()->nullable();
            $table->string('pw_ak_tempat_lahir', 30)->nullable();
            $table->string('pw_ak_tanggal_lahir', 10)->nullable();
            $table->string('pw_ak_pend_terakhir', 50)->nullable();
            $table->string('pw_ak_pekerjaan_utama', 50)->nullable();
            $table->string('pw_ak_pghsln_rt', 50)->nullable();
            $table->string('pw_ak_ustadz_kajian', 50)->nullable();
            $table->string('pw_ak_tempat_kajian', 50)->nullable();
            $table->boolean('pw_ak_tdk_hp')->nullable();
            $table->string('pw_ak_nomor_handphone', 20)->nullable();
            $table->string('pw_ak_no_kk', 16)->unique()->nullable();
            $table->string('pw_ak_kep_kel_kk', 70)->nullable();
            $table->string('pw_ak_file_kk', 255)->nullable();
            $table->string('pw_ik_nama_lengkap', 70)->nullable();
            $table->string('pw_ik_nama_kunyah', 70)->nullable();
            $table->string('pw_ik_status', 50)->nullable();
            $table->string('pw_ik_kewarganegaraan', 10)->nullable();
            $table->string('pw_ik_asal_negara', 50)->nullable();
            $table->string('pw_ik_kitas', 20)->nullable();
            $table->string('pw_ik_nik', 16)->unique()->nullable();
            $table->string('pw_ik_tempat_lahir', 30)->nullable();
            $table->string('pw_ik_tanggal_lahir', 10)->nullable();
            $table->string('pw_ik_pend_terakhir', 50)->nullable();
            $table->string('pw_ik_pekerjaan_utama', 50)->nullable();
            $table->string('pw_ik_pghsln_rt', 50)->nullable();
            $table->string('pw_ik_ustadz_kajian', 50)->nullable();
            $table->string('pw_ik_tempat_kajian', 50)->nullable();
            $table->boolean('pw_ik_tdk_hp')->nullable();
            $table->string('pw_ik_nomor_handphone', 20)->nullable();
            $table->boolean('pw_ik_kk_sama_ak')->nullable();
            $table->string('pw_ik_no_kk', 16)->unique()->nullable();
            $table->string('pw_ik_kep_kel_kk', 70)->nullable();
            $table->string('pw_ik_file_kk', 255)->nullable();
            $table->string('pw_w_status', 50)->nullable();
            $table->string('pw_w_hubungan', 50)->nullable();
            $table->string('pw_w_nama_lengkap', 70)->nullable();
            $table->string('pw_w_nama_kunyah', 70)->nullable();
            $table->string('pw_w_kewarganegaraan', 10)->nullable();
            $table->string('pw_w_asal_negara', 50)->nullable();
            $table->string('pw_w_kitas', 20)->nullable();
            $table->string('pw_w_nik', 16)->unique()->nullable();
            $table->string('pw_w_tempat_lahir', 30)->nullable();
            $table->string('pw_w_tanggal_lahir', 10)->nullable();
            $table->string('pw_w_pend_terakhir', 50)->nullable();
            $table->string('pw_w_pekerjaan_utama', 50)->nullable();
            $table->string('pw_w_pghsln_rt', 50)->nullable();
            $table->string('pw_w_ustadz_kajian', 50)->nullable();
            $table->string('pw_w_tempat_kajian', 50)->nullable();
            $table->boolean('pw_w_tdk_hp')->nullable();
            $table->string('pw_w_nomor_handphone', 20)->nullable();
            $table->string('pw_w_no_kk', 16)->unique()->nullable();
            $table->string('pw_w_kep_kel_kk', 70)->nullable();
            $table->string('pw_w_file_kk', 255)->nullable();
            $table->boolean('pw_al_ak_tgldi_ln')->nullable();
            $table->text('pw_al_ak_almt_ln')->nullable();
            $table->string('pw_al_ak_stts_rmh', 20)->nullable();
            $table->string('pw_al_ak_provinsi_id', 10)->nullable();
            $table->string('pw_al_ak_kabupaten_id', 10)->nullable();
            $table->string('pw_al_ak_kecamatan_id', 10)->nullable();
            $table->string('pw_al_ak_kelurahan_id', 10)->nullable();
            $table->string('pw_al_ak_rt', 10)->nullable();
            $table->string('pw_al_ak_rw', 10)->nullable();
            $table->text('pw_al_ak_alamat')->nullable();
            $table->string('pw_al_ak_kodepos', 10)->nullable();
            $table->boolean('pw_al_ik_sama_ak')->nullable();
            $table->boolean('pw_al_ik_tgldi_ln')->nullable();
            $table->text('pw_al_ik_almt_ln')->nullable();
            $table->string('pw_al_ik_stts_rmh', 20)->nullable();
            $table->string('pw_al_ik_provinsi_id', 10)->nullable();
            $table->string('pw_al_ik_kabupaten_id', 10)->nullable();
            $table->string('pw_al_ik_kecamatan_id', 10)->nullable();
            $table->string('pw_al_ik_kelurahan_id', 10)->nullable();
            $table->string('pw_al_ik_rt', 10)->nullable();
            $table->string('pw_al_ik_rw', 10)->nullable();
            $table->text('pw_al_ik_alamat')->nullable();
            $table->string('pw_al_ik_kodepos', 10)->nullable();
            $table->boolean('pw_al_w_tgldi_ln')->nullable();
            $table->text('pw_al_w_almt_ln')->nullable();
            $table->string('pw_al_w_stts_rmh', 20)->nullable();
            $table->string('pw_al_w_provinsi_id', 10)->nullable();
            $table->string('pw_al_w_kabupaten_id', 10)->nullable();
            $table->string('pw_al_w_kecamatan_id', 10)->nullable();
            $table->string('pw_al_w_kelurahan_id', 10)->nullable();
            $table->string('pw_al_w_rt', 10)->nullable();
            $table->string('pw_al_w_rw', 10)->nullable();
            $table->text('pw_al_w_alamat')->nullable();
            $table->string('pw_al_w_kodepos', 10)->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('pendaftars');
    }
};
