<?php

namespace App\Filament\Resources;

use App\Filament\Resources\PendaftarResource\Pages;
use App\Filament\Resources\PendaftarResource\RelationManagers;
use App\Models\Pendaftar;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Illuminate\Support\Facades\Auth;

class PendaftarResource extends Resource
{
    protected static ?string $model = Pendaftar::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('walisantri_id')
                    ->maxLength(255),
                Forms\Components\TextInput::make('ps_qism')
                    ->maxLength(2),
                Forms\Components\TextInput::make('ps_qism_view')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kelas')
                    ->maxLength(2),
                Forms\Components\TextInput::make('ps_tahap')
                    ->maxLength(30),
                Forms\Components\TextInput::make('ps_desc_tahap')
                    ->maxLength(255),
                Forms\Components\TextInput::make('ps_nism')
                    ->maxLength(10),
                Forms\Components\Toggle::make('ps_belum_nism'),
                Forms\Components\TextInput::make('ps_nama_lengkap')
                    ->maxLength(50),
                Forms\Components\TextInput::make('ps_nama_panggilan')
                    ->maxLength(50),
                Forms\Components\TextInput::make('ps_nisn')
                    ->maxLength(10),
                Forms\Components\Toggle::make('ps_belum_nisn'),
                Forms\Components\TextInput::make('ps_kewarganegaraan')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_asal_negara')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kitas')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kartu_keluarga')
                    ->maxLength(16),
                Forms\Components\TextInput::make('ps_nik')
                    ->maxLength(16),
                Forms\Components\Toggle::make('ps_belum_punya_nik'),
                Forms\Components\TextInput::make('ps_jeniskelamin')
                    ->maxLength(15),
                Forms\Components\TextInput::make('ps_tempat_lahir')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_tanggal_lahir')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_umur')
                    ->maxLength(3),
                Forms\Components\TextInput::make('ps_agama')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_cita_cita')
                    ->maxLength(30),
                Forms\Components\TextInput::make('ps_cita_cita_lainnya')
                    ->maxLength(30),
                Forms\Components\TextInput::make('ps_anak_ke')
                    ->maxLength(2),
                Forms\Components\TextInput::make('ps_jumlah_saudara')
                    ->maxLength(2),
                Forms\Components\Toggle::make('ps_tdk_hp'),
                Forms\Components\TextInput::make('ps_nomor_handphone')
                    ->tel()
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_email')
                    ->email()
                    ->maxLength(50),
                Forms\Components\TextInput::make('ps_akun_medsos')
                    ->maxLength(40),
                Forms\Components\TextInput::make('ps_akun_medsos_aktif')
                    ->maxLength(40),
                Forms\Components\TextInput::make('ps_hobi')
                    ->maxLength(40),
                Forms\Components\TextInput::make('ps_hobi_lainnya')
                    ->maxLength(40),
                Forms\Components\TextInput::make('ps_aktivitaspend')
                    ->maxLength(30),
                Forms\Components\TextInput::make('ps_peng_pend_agama')
                    ->maxLength(30),
                Forms\Components\TextInput::make('ps_peng_pend_formal')
                    ->maxLength(40),
                Forms\Components\TextInput::make('ps_bya_sklh')
                    ->maxLength(50),
                Forms\Components\TextInput::make('ps_status_mampu')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_rincian_status_mampu')
                    ->maxLength(255),
                Forms\Components\TextInput::make('ps_mendaftar_keinginan')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_mendaftar_keinginan_lainnya')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_keb_khus')
                    ->maxLength(50),
                Forms\Components\Textarea::make('ps_keb_khus_lainnya')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_keb_dis')
                    ->maxLength(50),
                Forms\Components\Textarea::make('ps_keb_dis_lainnya')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_peny_fisik')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_peny_non_fisik')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_nomor_kip')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_nama_kpl_kel')
                    ->maxLength(50),
                Forms\Components\TextInput::make('ps_file_kip')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_al_s_status_mukim')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_al_s_stts_tptgl')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_provinsi_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_kabupaten_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_kecamatan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_kelurahan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_al_s_rt')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_al_s_rw')
                    ->maxLength(10),
                Forms\Components\Textarea::make('ps_al_s_alamat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_kodepos')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_al_s_jarak')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_al_s_transportasi')
                    ->maxLength(10),
                Forms\Components\TextInput::make('ps_al_s_waktu_tempuh')
                    ->maxLength(10),
                Forms\Components\Textarea::make('ps_al_s_koordinat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_hafalan')
                    ->maxLength(2),
                Forms\Components\TextInput::make('ps_kkh_keberadaan')
                    ->maxLength(50),
                Forms\Components\Textarea::make('ps_kkh_keberadaan_nama_mhd')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_keberadaan_lokasi_mhd')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_keberadaan_rumah_keg')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkh_fasilitas_gawai'),
                Forms\Components\Textarea::make('ps_kkh_fasilitas_gawai_medsos')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_fasilitas_gawai_medsos_daftar')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_fasilitas_gawai_medsos_aktif')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_kkh_fasilitas_gawai_medsos_menutup')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kkh_medsos_sering')
                    ->maxLength(20),
                Forms\Components\Textarea::make('ps_kkh_medsos_sering_lainnya')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkh_medsos_group'),
                Forms\Components\Textarea::make('ps_kkh_medsos_group_nama')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_medsos_group_bidang_keg')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_bacaan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkh_bacaan_cara_dapat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_sakit_serius'),
                Forms\Components\Textarea::make('ps_kkes_sakit_serius_kapan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkes_sakit_serius_nama_penyakit')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_terapi'),
                Forms\Components\Textarea::make('ps_kkes_terapi_kapan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkes_terapi_nama_terapi')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_kambuh'),
                Forms\Components\Textarea::make('ps_kkes_kambuh_nama_penyakit')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_alergi'),
                Forms\Components\Textarea::make('ps_kkes_alergi_nama_alergi')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_pantangan'),
                Forms\Components\Textarea::make('ps_kkes_pantangan_nama')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Textarea::make('ps_kkes_pantangan_alasan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_psikologis'),
                Forms\Components\Textarea::make('ps_kkes_psikologis_kapan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\Toggle::make('ps_kkes_gangguan'),
                Forms\Components\Textarea::make('ps_kkes_gangguan_kapan')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('ps_kadm_status')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_surat_subsidi')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_surat_kurang_mampu')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_atur_keuangan')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_penentuan_subsidi')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_hidup_sederhana')
                    ->maxLength(20),
                Forms\Components\TextInput::make('ps_kadm_kebijakan_subsidi')
                    ->maxLength(20),
                Forms\Components\TextInput::make('user_id')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_kartu_keluarga_santri')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_ak_nama_lengkap')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ak_nama_kunyah')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ak_status')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_kewarganegaraan')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_ak_asal_negara')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_kitas')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_ak_nik')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_ak_tempat_lahir')
                    ->maxLength(30),
                Forms\Components\TextInput::make('pw_ak_tanggal_lahir')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_ak_pend_terakhir')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_pekerjaan_utama')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_pghsln_rt')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_ustadz_kajian')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ak_tempat_kajian')
                    ->maxLength(50),
                Forms\Components\Toggle::make('pw_ak_tdk_hp'),
                Forms\Components\TextInput::make('pw_ak_nomor_handphone')
                    ->tel()
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_ak_no_kk')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_ak_kep_kel_kk')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ak_file_kk')
                    ->maxLength(255),
                Forms\Components\TextInput::make('pw_ik_nama_lengkap')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ik_nama_kunyah')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ik_status')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_kewarganegaraan')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_ik_asal_negara')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_kitas')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_ik_nik')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_ik_tempat_lahir')
                    ->maxLength(30),
                Forms\Components\TextInput::make('pw_ik_tanggal_lahir')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_ik_pend_terakhir')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_pekerjaan_utama')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_pghsln_rt')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_ustadz_kajian')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_ik_tempat_kajian')
                    ->maxLength(50),
                Forms\Components\Toggle::make('pw_ik_tdk_hp'),
                Forms\Components\TextInput::make('pw_ik_nomor_handphone')
                    ->tel()
                    ->maxLength(20),
                Forms\Components\Toggle::make('pw_ik_kk_sama_ak'),
                Forms\Components\TextInput::make('pw_ik_no_kk')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_ik_kep_kel_kk')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_ik_file_kk')
                    ->maxLength(255),
                Forms\Components\TextInput::make('pw_w_status')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_hubungan')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_nama_lengkap')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_w_nama_kunyah')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_w_kewarganegaraan')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_w_asal_negara')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_kitas')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_w_nik')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_w_tempat_lahir')
                    ->maxLength(30),
                Forms\Components\TextInput::make('pw_w_tanggal_lahir')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_w_pend_terakhir')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_pekerjaan_utama')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_pghsln_rt')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_ustadz_kajian')
                    ->maxLength(50),
                Forms\Components\TextInput::make('pw_w_tempat_kajian')
                    ->maxLength(50),
                Forms\Components\Toggle::make('pw_w_tdk_hp'),
                Forms\Components\TextInput::make('pw_w_nomor_handphone')
                    ->tel()
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_w_no_kk')
                    ->maxLength(16),
                Forms\Components\TextInput::make('pw_w_kep_kel_kk')
                    ->maxLength(70),
                Forms\Components\TextInput::make('pw_w_file_kk')
                    ->maxLength(255),
                Forms\Components\Toggle::make('pw_al_ak_tgldi_ln'),
                Forms\Components\Textarea::make('pw_al_ak_almt_ln')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_ak_stts_rmh')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_al_ak_provinsi_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ak_kabupaten_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ak_kecamatan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ak_kelurahan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ak_rt')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ak_rw')
                    ->maxLength(10),
                Forms\Components\Textarea::make('pw_al_ak_alamat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_ak_kodepos')
                    ->maxLength(10),
                Forms\Components\Toggle::make('pw_al_ik_sama_ak'),
                Forms\Components\Toggle::make('pw_al_ik_tgldi_ln'),
                Forms\Components\Textarea::make('pw_al_ik_almt_ln')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_ik_stts_rmh')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_al_ik_provinsi_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ik_kabupaten_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ik_kecamatan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ik_kelurahan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ik_rt')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_ik_rw')
                    ->maxLength(10),
                Forms\Components\Textarea::make('pw_al_ik_alamat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_ik_kodepos')
                    ->maxLength(10),
                Forms\Components\Toggle::make('pw_al_w_tgldi_ln'),
                Forms\Components\Textarea::make('pw_al_w_almt_ln')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_w_stts_rmh')
                    ->maxLength(20),
                Forms\Components\TextInput::make('pw_al_w_provinsi_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_w_kabupaten_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_w_kecamatan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_w_kelurahan_id')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_w_rt')
                    ->maxLength(10),
                Forms\Components\TextInput::make('pw_al_w_rw')
                    ->maxLength(10),
                Forms\Components\Textarea::make('pw_al_w_alamat')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Forms\Components\TextInput::make('pw_al_w_kodepos')
                    ->maxLength(10),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('walisantri_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_qism')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_qism_view')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kelas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_tahap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_desc_tahap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nism')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_belum_nism')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_nama_lengkap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nama_panggilan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nisn')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_belum_nisn')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_kewarganegaraan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_asal_negara')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kitas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kartu_keluarga')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nik')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_belum_punya_nik')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_jeniskelamin')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_tempat_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_tanggal_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_umur')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_agama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_cita_cita')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_cita_cita_lainnya')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_anak_ke')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_jumlah_saudara')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_tdk_hp')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_nomor_handphone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_email')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_akun_medsos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_akun_medsos_aktif')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_hobi')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_hobi_lainnya')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_aktivitaspend')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_peng_pend_agama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_peng_pend_formal')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_bya_sklh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_status_mampu')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_rincian_status_mampu')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_mendaftar_keinginan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_mendaftar_keinginan_lainnya')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_keb_khus')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_keb_dis')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nomor_kip')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_nama_kpl_kel')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_file_kip')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_status_mukim')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_stts_tptgl')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_provinsi_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kabupaten_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kecamatan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kelurahan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_rw')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kodepos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_jarak')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_transportasi')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_al_s_waktu_tempuh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_hafalan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kkh_keberadaan')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_kkh_fasilitas_gawai')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_kkh_fasilitas_gawai_medsos_menutup')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kkh_medsos_sering')
                    ->searchable(),
                Tables\Columns\IconColumn::make('ps_kkh_medsos_group')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_sakit_serius')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_terapi')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_kambuh')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_alergi')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_pantangan')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_psikologis')
                    ->boolean(),
                Tables\Columns\IconColumn::make('ps_kkes_gangguan')
                    ->boolean(),
                Tables\Columns\TextColumn::make('ps_kadm_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_surat_subsidi')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_surat_kurang_mampu')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_atur_keuangan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_penentuan_subsidi')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_hidup_sederhana')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ps_kadm_kebijakan_subsidi')
                    ->searchable(),
                Tables\Columns\TextColumn::make('user_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_kartu_keluarga_santri')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_nama_lengkap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_nama_kunyah')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_kewarganegaraan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_asal_negara')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_kitas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_nik')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_tempat_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_tanggal_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_pend_terakhir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_pekerjaan_utama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_pghsln_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_ustadz_kajian')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_tempat_kajian')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_ak_tdk_hp')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_ak_nomor_handphone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_no_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_kep_kel_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ak_file_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_nama_lengkap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_nama_kunyah')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_kewarganegaraan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_asal_negara')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_kitas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_nik')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_tempat_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_tanggal_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_pend_terakhir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_pekerjaan_utama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_pghsln_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_ustadz_kajian')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_tempat_kajian')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_ik_tdk_hp')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_ik_nomor_handphone')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_ik_kk_sama_ak')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_ik_no_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_kep_kel_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_ik_file_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_status')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_hubungan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_nama_lengkap')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_nama_kunyah')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_kewarganegaraan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_asal_negara')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_kitas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_nik')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_tempat_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_tanggal_lahir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_pend_terakhir')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_pekerjaan_utama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_pghsln_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_ustadz_kajian')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_tempat_kajian')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_w_tdk_hp')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_w_nomor_handphone')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_no_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_kep_kel_kk')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_w_file_kk')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_al_ak_tgldi_ln')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_al_ak_stts_rmh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_provinsi_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_kabupaten_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_kecamatan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_kelurahan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_rw')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ak_kodepos')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_al_ik_sama_ak')
                    ->boolean(),
                Tables\Columns\IconColumn::make('pw_al_ik_tgldi_ln')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_al_ik_stts_rmh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_provinsi_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_kabupaten_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_kecamatan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_kelurahan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_rw')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_ik_kodepos')
                    ->searchable(),
                Tables\Columns\IconColumn::make('pw_al_w_tgldi_ln')
                    ->boolean(),
                Tables\Columns\TextColumn::make('pw_al_w_stts_rmh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_provinsi_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_kabupaten_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_kecamatan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_kelurahan_id')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_rt')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_rw')
                    ->searchable(),
                Tables\Columns\TextColumn::make('pw_al_w_kodepos')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListPendaftars::route('/'),
            'create' => Pages\CreatePendaftar::route('/create'),
            'view' => Pages\ViewPendaftar::route('/{record}'),
            'edit' => Pages\EditPendaftar::route('/{record}/edit'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->where('ps_kartu_keluarga', Auth::user()->username);
    }
}
